### ISSUE TITLE
environment.yml incorrect package spec

### ISSUE THREAD

**Issue by swelborn** [als-computing/microct#29]
Hello. There was a recent update to `environment.yml` that causes the following:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge::ipympl==0.86
 ```
 
 I think this should be
 
 ```
  - conda-forge::ipympl==0.8.6
  ```
  
If you want to pin the version.

**Comment by davramov** [comment]
Closing this issue because it was addressed in my PR: https://github.com/als-computing/microct/pull/31
