### ISSUE TITLE
nersc-containerfile branch tomorecon_nersc_mpi_hdf5 build issue

### ISSUE THREAD

**Issue by rajasriramoju** [als-computing/microct#30]
The [containerfile](https://github.com/als-computing/microct/blob/nersc-containerfile/legacy/tomorecon_nersc_mpi_hdf5/Containerfile) committed was used for building tomorecon_nersc_mpi_hdf5
:1.0 on harbor. I tried rebuilding the container again with this file, but am currently seeing warnings with libmamba. The build reaches step 13/26 and shows the following warning and does not proceed with the build. It proceeds to wait for an indefinite amount of time. This issue needs to be looked into.
<img width="984" alt="Screenshot 2024-12-02 at 7 44 09 PM" src="https://github.com/user-attachments/assets/6b3bc5e3-787b-4ef6-99c9-2d6f505d63a7">

**Comment by davramov** [comment]
I have been looking into this today. By adding a few `which mamba` statements, I found out it seems like mamba gets uninstalled while it is installing things. Very odd.

```Dockerfile
RUN conda install -n base --yes -c conda-forge mamba
RUN which mamba
# returns:
# STEP 13/26: RUN which mamba                          
# /opt/miniconda/bin/mamba      

# # uninstalling mpi removes essential packages, so re-add
RUN mamba install --yes astropy cartopy cython cfitsio "dask[distributed]" scipy scikit-learn scikit-image numba h5py joblib pandas statsmodels _libgcc_mutex
# At some time during STEP 14/26  mamba is uninstalled

RUN which mamba
# returns:
# STEP 15/26: RUN which mamba
# Error: building at STEP "RUN which mamba": while running runtime: exit status 1
```

Addressing this in my PR by reorganizing these installation steps:
https://github.com/als-computing/microct/pull/31
```
RUN conda install --yes -c conda-forge python=3.10 mamba \
    && mamba install --yes -c conda-forge \
       mamba astropy cartopy cython cfitsio "dask[distributed]" scipy scikit-learn scikit-image numba h5py joblib pandas statsmodels _libgcc_mutex \
    && mamba install --yes -c conda-forge -c astra-toolbox -c simpleitk \
       mamba astra-toolbox tifffile tomopy dxchange svmbir itk simpleitk pyfftw natsort olefile tqdm zarr
```

**Comment by davramov** [comment]
Closing this because it is addressed in my PR: https://github.com/als-computing/microct/pull/31
